// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// read_joystick //
// ------------- //

#define read_joystick_wrap_target 0
#define read_joystick_wrap 11
#define read_joystick_pio_version 0

static const uint16_t read_joystick_program_instructions[] = {
            //     .wrap_target
    0xf301, //  0: set    pins, 1                [19]
    0xe000, //  1: set    pins, 0                    
    0xe02f, //  2: set    x, 15                      
    0x2003, //  3: wait   0 gpio, 3                  
    0x4003, //  4: in     pins, 3                    
    0x2083, //  5: wait   1 gpio, 3                  
    0x0043, //  6: jmp    x--, 3                     
    0xc020, //  7: irq    wait 0                     
    0xe03f, //  8: set    x, 31                      
    0xbf42, //  9: nop                           [31]
    0xbf42, // 10: nop                           [31]
    0x0049, // 11: jmp    x--, 9                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program read_joystick_program = {
    .instructions = read_joystick_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config read_joystick_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + read_joystick_wrap_target, offset + read_joystick_wrap);
    return c;
}

#include "hardware/clocks.h"
// Set up the FFB handshake program. Uses only the trigger pin.
void read_joystick_program_init(
    PIO pio, uint sm, uint offset, uint freq,
    uint pin_trigger, uint pin_clk, uint pin_d0, uint pin_d1, uint pin_d2
    )
{
    pio_sm_config c = read_joystick_program_get_default_config(offset);
    sm_config_set_set_pins(&c, pin_trigger, 1);
    sm_config_set_in_pins(&c, pin_d0);
    sm_config_set_in_shift(&c, true, true, 24);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    // Connect PIO to the trigger pin, and set its direction
    pio_gpio_init(pio, pin_trigger);
    pio_gpio_init(pio, pin_clk);
    pio_gpio_init(pio, pin_d0);
    pio_gpio_init(pio, pin_d1);
    pio_gpio_init(pio, pin_d2);
    pio_sm_set_consecutive_pindirs(pio, sm, pin_trigger, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, pin_clk, 1, false);
    pio_sm_set_consecutive_pindirs(pio, sm, pin_d0, 3, false);
    float div = clock_get_hz(clk_sys) / freq;
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

