// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// ffb_handshake //
// ------------- //

#define ffb_handshake_wrap_target 0
#define ffb_handshake_wrap 9
#define ffb_handshake_pio_version 0

static const uint16_t ffb_handshake_program_instructions[] = {
            //     .wrap_target
    0xe046, //  0: set    y, 6                       
    0x80a0, //  1: pull   block                      
    0x6030, //  2: out    x, 16                      
    0xa842, //  3: nop                           [8] 
    0x0043, //  4: jmp    x--, 3                     
    0x6030, //  5: out    x, 16                      
    0xe101, //  6: set    pins, 1                [1] 
    0xf000, //  7: set    pins, 0                [16]
    0x0046, //  8: jmp    x--, 6                     
    0x0081, //  9: jmp    y--, 1                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ffb_handshake_program = {
    .instructions = ffb_handshake_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ffb_handshake_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ffb_handshake_wrap_target, offset + ffb_handshake_wrap);
    return c;
}

#include "hardware/clocks.h"
// Set up the FFB handshake program. Uses only the trigger pin.
void ffb_handshake_program_init(
    PIO pio, uint sm, uint offset, uint freq, uint pin_trigger
    )
{
    pio_sm_config c = ffb_handshake_program_get_default_config(offset);
    sm_config_set_set_pins(&c, pin_trigger, 1);
    // Connect PIO to the trigger pin, and set its direction
    pio_gpio_init(pio, pin_trigger);
    pio_sm_set_consecutive_pindirs(pio, sm, pin_trigger, 1, true);
    float div = clock_get_hz(clk_sys) / freq;
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

